### ISSUE TITLE
User role account can deploy a k8s cluster 

### ISSUE THREAD

**Issue by kiranchavala** [kubernetes-sigs/cluster-api-provider-cloudstack#304] opened 2023-08-16 04:27 UTC
/kind feature

Currently, only a domain role account can deploy a Kubernetes cluster 

https://cluster-api-cloudstack.sigs.k8s.io/topics/cloudstack-permissions

Extending it to a user role account will be useful for cases where the admin does not want to give too many permissions to the end user.

<img width="738" alt="Screenshot 2023-08-16 at 9 55 54 AM" src="https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/assets/1401014/2f2d87da-a5e1-4bbd-b8c6-398b98521a3b">

**Comment by rohityadavcloud** [comment] 2023-08-23 11:07
Dupe of https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/303

**Comment by rohityadavcloud** [comment] 2023-08-23 14:30
@kiranchavala I think with a normal user, it can work once you know the cluster IP (say in case of shared network). So, I suppose as long as a user provided (public) IP address is valid and accepted by cloudstack (i.e. both user can list public ips and a free public ip provided by user is used by cloudstack) then this use-case can work cc @weizhouapache

**Comment by rohityadavcloud** [comment] 2023-08-29 12:33
Thanks @kiranchavala closing as it dupes https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/303

**Closed by rohityadavcloud** 2023-08-29 12:33 UTC
Labels: kind/feature
